### ISSUE TITLE
Do we need more intro?

### ISSUE THREAD

**Issue by StackScribe** [afzal442/keptn-pg-killerway#48]
Put your head in thinking-about-anything-else mode.  Is the beginning of this too abrupt?
Maybe just a sentence like "This tutorial illustrates how Keptn can orchestrate..."  And then
"We will do the following:"

I'm just thinking that, if you ask me about my goals in life, deploying a microservice is not
high on the list ;-)  But understanding how Keptn does its magic might be of interest ;-)

**Comment by agardnerIT** [comment]
Closing as stale
