### ISSUE TITLE
Do we need to introduce kilrcoda interface?

### ISSUE THREAD

**Issue by StackScribe** [afzal442/keptn-pg-killerway#49]
Do we just assume that people will figure out that they can click a command in the right frame and it will execute in the left frame?
They can click in the left frame and issue shell commands on their own.

Also, should we warn them that, once they start this exercise, they need to sit there and finish it?  Their environment will be shut down 1 hour after they begin or if it is idle for 5 minutes?

**Comment by agardnerIT** [comment]
Closing as stale
