### ISSUE TITLE
How to get to github repo

### ISSUE THREAD

**Issue by StackScribe** [afzal442/keptn-pg-killerway#50]
We just tell them to look at their github repo which is just a bit non-trivial since they didn't create it manually on the github site.  I looked around the right frame and found the string -- but then, I am used to github so I knew what I was looking for.  Mirablile dictu!  It was a link so I right-clicked it.  And did not end up where I wanted to.

So then I selected it and copied it, opened a new tab, and pasted the string in and that worked.

One other thought -- I can't find the exact string right now but somewhere you say that we are using github but you can use any Git -- it did not say that, for this tutorial, you have to use github.  I don't know what would happen if someone tried to do this with, say, BitBucket and I don't care to test it.

**Comment by agardnerIT** [comment]
Closing as stale
