### ISSUE TITLE
[ENH] Update tutorial to keptn 0.17.0

### ISSUE THREAD

**Issue by afzal442** [afzal442/keptn-pg-killerway#52]
The `env` variable for `keptn` CLI version chosen is 0.15.1. Is this desirable? I'm a bit confused here since we are referencing users to official docs installation guide page with 0.16.1V in the `killercoda` platform. 

cc @agardnerIT

**Comment by agardnerIT** [comment]
Software BOM for v0.17.0 tutorial (items requiring an update are marked):

- k3d version: v5.3.0
- kubectl = v1.22.6
- GitHub CLI = v1.22.6 (upgrade required)
- Keptn version = 0.17.0
- JES Version = 0.2.3
- Keptn Prometheus Service Version = 0.8.3

Also note the helm chart value breaking changes from <0.16 to >0.17:

`--set=control-plane.apiGatewayNginx.type=LoadBalancer` becomes `--set=apiGatewayNginx.type=LoadBalancer`
