### ISSUE TITLE
Keptn Demo Broken

### ISSUE THREAD

**Issue by agardnerIT** [afzal442/keptn-pg-killerway#73]
There have now been 2 reports of the Keptn demo being broken:

```
Once I authenticate to Github the script creates a repo but then it fails:  
ubuntu $ ~/setup_keptn.sh

=================================================================================
 Creating brand new Git repo (keptndemo) on your GitHub.com account     
=================================================================================
✓ Created repository Someone/keptndemo on GitHub

=================================================================================
 Creating Keptn project (fulltour) and a Keptn service (helloservice)            
=================================================================================
Keptn CLI is already on the latest version ( 1.0.0 )! 
* Your Keptn CLI version: 1.0.0
* Keptn version 1.1.0 is available! Please visit https://keptn.sh/docs/1.1.x/operate/upgrade/ for more information.
* Your Keptn cluster version: 1.0.0
* To disable the daily version check, please execute:
 - keptn set config AutomaticVersionCheck false

Starting to create project
Error: Create project was unsuccessful.
upstream repository not found
```

**Comment by agardnerIT** [comment]
Seeing lots of this during install. Maybe temporary, may be important but it is a killercoda problem not Keptn:

```
E0124 23:13:02.297892   25726 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0124 23:13:02.325939   25726 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0124 23:13:02.367077   25726 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0124 23:13:02.423857   25726 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by agardnerIT** [comment]
Q on slack: `The first thing I encountered was that it hangs for a LONG time at this step: ubuntu $ kubectl -n keptn-jes wait --for condition=Available=True --timeout=${POD_WAIT_TIMEOUT_MINS}m deployment/job-executor-service.  It finally gets to "Installation Complete" after 11 minutes.`

The Job Executor Service (JES) needs to communicate with Keptn so until all the pods in the `keptn` namespace are running, the JES pod won't start.

Unfortunately the startup time has as much to do with the underlying infrastructure (provided for free by Killercoda) so there isn't much we can do here.

**Comment by agardnerIT** [comment]
So what's happening?

A few possibilities I see:

1) The user is attempting to run `setup_keptn.sh` on a preexisting repo. DO NOT DO THIS. Let the demo create a new repo every time you re-run the `setup_keptn.sh` script.
2) The Git PAT token doesn't have full repo access
3) This is a temporary / transient issue with the connection to GitHub (see below for explanation)


When the `setup_keptn.sh` [creates the project](https://github.com/afzal442/keptn-pg-killerway/blob/877034701854b453e9a126155419e8fe7b2a14ae/keptn-end-to-end-delivery/assets/scripts/setup_keptn.sh#L12), it issues the `keptn create project` command via CLI. The logic here might need improvement in case of failure. I'm not sure, it may already retry on failure but the repo definitely does exist (it is created independently by the `gh` CLI command) so something is clearly going wrong.

From there, all the other errors are cascading symptoms. If the Keptn project doesn't exist, everything else is doomed to fail.

**Comment by LeslieMurphy** [comment]
Hi @agardnerIT 

Regarding Slow startup time - I suggest adding a line into the script to tell the user "The job-executor-service takes up to 10 minutes to start; please be patient"

On the create project issue - item 1 is not it - I tried twice to make sure there was not a preexisting repo.  Item 2 - is there some other access I need to enable besides "repo"?

<img width="447" alt="image" src="https://user-images.githubusercontent.com/4464416/214464268-c687ebe6-fd52-49d7-976b-05645940643e.png">

**Comment by LeslieMurphy** [comment]
I tried again after adding almost every conceivable permission to the token.  Still get same failure.  A new GitHub repo was created but it is empty.

```
Starting to create project
Error: Create project was unsuccessful.
upstream repository not found
Starting to create service
Create service was unsuccessful
Error: Create service was unsuccessful. could not get stages of project fulltour: project not found
```

**Comment by LeslieMurphy** [comment]
Could it perhaps be that my username on GitHub is different than the userid?  Grasping at straws.

ubuntu $ git clone https://github.com/LeslieMurphy/keptdemo3.git
Cloning into 'keptdemo3'...
Username for 'https://github.com': les.murphy@xxxxxxxxxxxxxxx.com
Password for 'https://les.murphy@xxxxxxxxxxxxxxx.com@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/LeslieMurphy/keptdemo3.git/' not found

ubuntu $ git clone https://github.com/LeslieMurphy/keptndemo3.git
Cloning into 'keptndemo3'...
warning: You appear to have cloned an empty repository.

**Comment by agardnerIT** [comment]
Oh... It could? Tbh I didn't know that was possible with GitHub :)

**Comment by LeslieMurphy** [comment]
I will try again and see if it accepts my username with the token

**Comment by agardnerIT** [comment]
Also, there was a typo above. You wrote `keptdemo3` and it is `keptndemo3` with an `n`

**Comment by LeslieMurphy** [comment]
I know! I fat fingered it!  It is WORKING when I use my username! 

![image](https://user-images.githubusercontent.com/4464416/214611167-1de3b8cf-5993-4221-878c-3929add480dc.png)

**Comment by LeslieMurphy** [comment]
![image](https://user-images.githubusercontent.com/4464416/214611379-67ecc8ba-3ec0-47c5-8aaa-8758a2db5842.png)

**Comment by LeslieMurphy** [comment]
GitHub allows authentication using either the Username or email address.  If the email is used in the Keptn script for the token credentials, the script will create a repo but subsequently will fail.  Is there a way to improve the process to make it work in either case?

![image](https://user-images.githubusercontent.com/4464416/214612765-4739260e-78b5-4681-9115-72db952f618a.png)

**Comment by LeslieMurphy** [comment]
Here is a summary of the issue:

![image](https://user-images.githubusercontent.com/4464416/214614694-f8faa174-c253-4f2a-873a-bde29ca063bd.png)

**Comment by agardnerIT** [comment]
@LeslieMurphy we are updating to Keptn v1.1.0 and it might be nice to include this in that work (#74).

If I'm not mistaken, all we need here is to modify the `set_git_details.sh` and include a new additional parameter for GIT_EMAIL. Then if it is NOT set, we assume username and just use that, but if it IS set, we can accomodate your usecase.

Make sense?

**Comment by LeslieMurphy** [comment]
Hi Adam, are you proposing three prompts - one for email and one for username plus the token?  Could you instead extract the username from github after creating the repo?

If you first install jq this will do the trick:

`gh api 'https://api.github.com/user' | jq .login`

Result after using my github email address for authentication is:

"LeslieMurphy"

**Comment by agardnerIT** [comment]
That's a much better idea. thanks!

**Comment by agardnerIT** [comment]
@LeslieMurphy anything more to do here or can we close?

**Comment by LeslieMurphy** [comment]
I think we are all good on it. Sent from my iPhoneOn Mar 26, 2023, at 5:25 PM, Adam Gardner ***@***.***> wrote:﻿
@LeslieMurphy anything more to do here or can we close?
