### ISSUE TITLE
Remove Step 10 of install

### ISSUE THREAD

**Issue by agardnerIT** [afzal442/keptn-pg-killerway#79]
Step 10 of install attempts to `kubectl apply` a file that has never been cloned. It is also uneccessary as it is applied directly from the github source in the preceding lines.

Step 10 will therefore always fail (harmlessly) and should be removed.

All other step numbers should obviously be updated.

**Comment by agardnerIT** [comment]
@rakshitgondwal want to take this?

**Comment by Soumya-Kushwaha** [comment]
I can't find the file where this edit should be made

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal want to take this?

Yes sure! Please assign this to me. I'll raise a PR soon.
