### ISSUE TITLE
Killercoda keptn error 

### ISSUE THREAD

**Issue by JJena** [afzal442/keptn-pg-killerway#81]
While trying end to end delivery in killercoda, getting below error in these steps.

Step 4/10: Installing Keptn Control Plane

Step 5/10: Installing Prometheus 

Step 6/10: Installing Prometheus Service 

Step 7/10: Installing Job Executor Service

<img width="877" alt="image" src="https://user-images.githubusercontent.com/19985725/220190356-254ee330-04cc-4cc4-a968-f82a3bf379a9.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/19985725/220194068-9599cdd9-45cf-4d0b-8205-4de8b37a2ca3.png">

**Comment by agardnerIT** [comment]
`keptn status` will fail until `keptn auth` is executed because `keptn auth` create the required `.keptn` folder and files.
