### ISSUE TITLE
Use Killercoda-native not k3d (startup time improvements)

### ISSUE THREAD

**Issue by agardnerIT** [afzal442/keptn-pg-killerway#82]
# Background

Killercoda now supports Persistent Volume Claims. Previously, due to the inability to create PVCs, the demo has been using k3d.

Moving to a Killercoda natively supported cluster (and removing k3d) will:

- Decrease the amount of installed components
- Decrease the system complexity
- Decrease the technical debt (k3d was last updated a year ago)

In turn, the above will:
- Improve supportability
- Improve startup times

The end result for users is almost the same - a working in-browser Keptn v1 but this is a net benefit.

# Task

Remove k3d from the `intro_foreground.sh` and instead of an `ubuntu` image, move to a `kubernetes-kubeadm-1node` base image.

**Comment by rakshitgondwal** [comment]
I would like to take this up!

**Comment by rakshitgondwal** [comment]
Hey @agardnerIT ! Thank you for assigning me this. I am trying to work on this but I can't get around the ubuntu image thing. What I can understand from above is that I'll need to change the `Initialising Kubernetes` step in `intro_foreground.sh`. In this step, we are installing k3d and then creating a cluster on it. Now to remove k3d I'll need to remove this step if I'm not wrong but where do I need to change the `ubuntu` image to `kubernetes-kubeadm-1node` image?

**Comment by rakshitgondwal** [comment]
Hey @agardnerIT! I removed the step 2 and updated the image id to `kubernetes-kubeadm-1node` in index.json.
Now when I'm trying to run the demo, in the last step of checking the pods, I guess there is some issue. Can you have a look on these?
![Screenshot from 2023-03-04 22-53-39](https://user-images.githubusercontent.com/98955085/222920109-c13a53fd-3556-4cc8-aa73-4d7aa5d11efa.png)

**Comment by agardnerIT** [comment]
These instructions are purely waiting for the pods to signal `Ready` or `Running`. So something is happening to prevent the pods starting.

I can see an error there for Prometheus and the TLS handshake was given to me when I was simply doing a `kubectl -n monitoring get pods`.

This feels like a Killercoda environment specific issue. I'd join the Killercoda slack and ask for assistance there. I can't really help here, it's outside my area of knowledge. But it doesn't look like a Keptn issue in particular.

**Comment by rakshitgondwal** [comment]
Hey @agardnerIT! I reached out to the Killercoda team on their slack and found out that we are installing a lot of resources, so we'll have to switch to a large k8s image with two nodes `kubernetes-kubeadm-2nodes`. 
I'll raise a PR for this asap.
