### ISSUE TITLE
502 Bad Gateway, necessary to run kubectl port-forward

### ISSUE THREAD

**Issue by wuestkamp** [afzal442/keptn-pg-killerway#85]
The scenario on https://killercoda.com/keptn/scenario/keptn-end-to-end-delivery fails with:

```
Error: authentication was not successful: error with status code 502
```

It works if we execute the following before trying to open the Kepn interface in the browser or before running `keptn auth ...`:

```
kubectl -n keptn port-forward --address 0.0.0.0 service/api-gateway-nginx 8080:80
```

Not sure why this worked before without this? Maybe something was changed on the way Keptn is installed, maybe something changed on Killercoda?

Discussion also in Slack [here](https://app.slack.com/client/T038VAWTCS3/C03972JUWQ5/thread/C03972JUWQ5-1681418650.776829?cdn_fallback=2).

**Comment by afzal442** [comment]
Yes! Nice caught. I had been noticing the same since I found that magic stuff from Adam. I too got surprised then. 😄
