### ISSUE TITLE
error in remediation stage

### ISSUE THREAD

**Issue by jorgerojasro** [afzal442/keptn-pg-killerway#92]
controlplane $ ./self_healing
bash: ./self_healing: Is a directory
controlplane $ ./self_healing.sh 
=======================================================
Add Self-Healing (scaling with Helm) to production
=======================================================
Already up to date.
On branch production
Your branch is up to date with 'origin/production'.

nothing to commit, working tree clean
Everything up-to-date

==============================
Add Keptn Remediation File
==============================
fatal: A branch named 'production' already exists.
On branch production
Your branch is up to date with 'origin/production'.

nothing to commit, working tree clean
Everything up-to-date

=============================================================================================
Link Remediation to Action (Modify job/config.yaml. Use helm to action the scaling request)
=============================================================================================
cp: cannot stat '/root/self_healing/job/config.yaml': No such file or directory
On branch production
Your branch is up to date with 'origin/production'.

nothing to commit, working tree clean
Everything up-to-date

====================================================
 Dummy problem created as remediation_trigger.json
====================================================

**Comment by agardnerIT** [comment]
Thanks for the report. I will look into this tomorrow.
